version: "3.4"

networks:
  default:

services:
  tg_bot:
    container_name: ava-bot-tg_bot
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./tg_bot:/opt/app/tg_bot
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    env_file:
      - .env


  redis:
    container_name: ava-bot-redis
    image: library/redis:7.2.2
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    networks:
      - default
    volumes:
    - ./.docker_data/redis:/data
    env_file:
      - .env


  postgres:
    container_name: ava-bot-postgres
    image: library/postgres:13
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - ./.docker_data/postgres:/var/lib/postgresql/data
    env_file:
      - .env


volumes:
  .docker_data:
  